version: "3.6"

services:
  db:
    image: postgres:12
    container_name: my_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: test_db
    ports:
      - '5432:5432'
    volumes:
      - ./schema/init.sql:/docker-entrypoint-initdb.d/init.sql
